name: Snyk SCA, Code, IaC and Container CLI monitor example

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SNYK_API: https://app.eu.snyk.io/api
  
jobs:
  build:
    name: Test and build
    environment: snyk-npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Setup Snyk + snyk-to-html # For information about the required commands for generating an HTML report see https://github.com/snyk/snyk-to-html
        run: |
          npm install snyk -g
          npm install snyk-to-html -g
          snyk auth ${{ secrets.SECRETS_TEST_SNYK_AUTH }}

      - name: Snyk Open Source
        run: |
          snyk monitor
        # For a list of additional available flags/options see: https://docs.snyk.io/snyk-cli/commands

      - name: Snyk Code
        run: |
          snyk code test || true
        # Remove || true to fail if there are vulnerabilities

      - name: Snyk Container
        run: |
          docker build . -t yourimage:tag
          snyk container monitor yourimage:tag --file=Dockerfile
        # Rename your image, for testing and failing please add snyk container test before snyk container monitor

      - name: Snyk IaC
        run: |
          snyk iac test || true
        # Remove || true to fail if there are vulnerabilities
